### ISSUE TITLE
Flexible start year

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/B-Tax#78]
B-Tax's interaction with TaxCalc can allow for different start years, but we don't currently update the default business tax parameters to reflect different start years.  

We should update the default parameter json to capture the changes in tax parameters over time under current law (e.g. the phase out of bonus depreciation).

@MattHJensen - do we want users to be able to go back in time - or just choose a start year from 2016 forward?

@PeterDSteinberg  - what would be the best way to add these defaults to the json file?  Do I just enter a list for the default parameters where there is a scalar now?

**Comment by MattHJensen** [comment]
> @MattHJensen - do we want users to be able to go back in time - or just choose a start year from 2016 forward?

@jdebacker,

For TC, we find it useful to allow users to go back in time so that they can compare against SOI aggregate statistics for 2013 or 2014.

What is probably more relevant for B-Tax is that it can also be useful for someone who wants to know, "what would the world look like if this policy had been enacted instead of that one." 

I advocate for allowing it.

**Comment by jdebacker** [comment]
@MattHJensen  - sounds reasonable.  Was mainly hoping not to have to look at the tax code for additional years!  I'll update when I get an idea how @PeterDSteinberg  would like me to format these objects.

**Comment by jdebacker** [comment]
Closed via PR #124
